name: Deploy Docusaurus site to GitHub Pages

on:
  push:
    branches:
      - main
    paths:
      - 'docs-site/**'

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        working-directory: ./docs-site
        run: npm ci --legacy-peer-deps

      - name: Build site
        working-directory: ./docs-site
        run: npm run build

      - name: Debug - List build directory contents
        working-directory: ./docs-site
        run: ls -la build/

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs-site/build
          publish_branch: gh-pages
